// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: adrs.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createADRWithNextSequence = `-- name: CreateADRWithNextSequence :one
INSERT INTO adrs (tenant_id, project_id, sequence, title, status, context, decision, drivers, options, consequences, created_by, agent_session_id)
VALUES (
    $1, $2,
    (SELECT COALESCE(MAX(sequence), 0) + 1 FROM adrs WHERE project_id = $2),
    $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, tenant_id, project_id, sequence, title, status, context, decision, drivers, options, consequences, created_by, agent_session_id, created_at, updated_at
`

type CreateADRWithNextSequenceParams struct {
	TenantID       uuid.UUID       `json:"tenant_id"`
	ProjectID      uuid.UUID       `json:"project_id"`
	Title          string          `json:"title"`
	Status         string          `json:"status"`
	Context        string          `json:"context"`
	Decision       string          `json:"decision"`
	Drivers        []string        `json:"drivers"`
	Options        json.RawMessage `json:"options"`
	Consequences   json.RawMessage `json:"consequences"`
	CreatedBy      pgtype.UUID     `json:"created_by"`
	AgentSessionID pgtype.UUID     `json:"agent_session_id"`
}

func (q *Queries) CreateADRWithNextSequence(ctx context.Context, arg CreateADRWithNextSequenceParams) (Adr, error) {
	row := q.db.QueryRow(ctx, createADRWithNextSequence,
		arg.TenantID,
		arg.ProjectID,
		arg.Title,
		arg.Status,
		arg.Context,
		arg.Decision,
		arg.Drivers,
		arg.Options,
		arg.Consequences,
		arg.CreatedBy,
		arg.AgentSessionID,
	)
	var i Adr
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Sequence,
		&i.Title,
		&i.Status,
		&i.Context,
		&i.Decision,
		&i.Drivers,
		&i.Options,
		&i.Consequences,
		&i.CreatedBy,
		&i.AgentSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getADRByID = `-- name: GetADRByID :one
SELECT id, tenant_id, project_id, sequence, title, status, context, decision, drivers, options, consequences, created_by, agent_session_id, created_at, updated_at FROM adrs WHERE id = $1 AND tenant_id = $2
`

type GetADRByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetADRByID(ctx context.Context, arg GetADRByIDParams) (Adr, error) {
	row := q.db.QueryRow(ctx, getADRByID, arg.ID, arg.TenantID)
	var i Adr
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Sequence,
		&i.Title,
		&i.Status,
		&i.Context,
		&i.Decision,
		&i.Drivers,
		&i.Options,
		&i.Consequences,
		&i.CreatedBy,
		&i.AgentSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listADRsByProject = `-- name: ListADRsByProject :many
SELECT id, tenant_id, project_id, sequence, title, status, context, decision, drivers, options, consequences, created_by, agent_session_id, created_at, updated_at FROM adrs WHERE project_id = $1 AND tenant_id = $2
ORDER BY sequence ASC, id ASC
LIMIT $3
`

type ListADRsByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListADRsByProject(ctx context.Context, arg ListADRsByProjectParams) ([]Adr, error) {
	rows, err := q.db.Query(ctx, listADRsByProject, arg.ProjectID, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Adr{}
	for rows.Next() {
		var i Adr
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Sequence,
			&i.Title,
			&i.Status,
			&i.Context,
			&i.Decision,
			&i.Drivers,
			&i.Options,
			&i.Consequences,
			&i.CreatedBy,
			&i.AgentSessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listADRsByProjectAfter = `-- name: ListADRsByProjectAfter :many
SELECT id, tenant_id, project_id, sequence, title, status, context, decision, drivers, options, consequences, created_by, agent_session_id, created_at, updated_at FROM adrs
WHERE project_id = $1 AND tenant_id = $2
  AND (sequence > $3 OR (sequence = $3 AND id > $4))
ORDER BY sequence ASC, id ASC
LIMIT $5
`

type ListADRsByProjectAfterParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Sequence  int32     `json:"sequence"`
	ID        uuid.UUID `json:"id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListADRsByProjectAfter(ctx context.Context, arg ListADRsByProjectAfterParams) ([]Adr, error) {
	rows, err := q.db.Query(ctx, listADRsByProjectAfter,
		arg.ProjectID,
		arg.TenantID,
		arg.Sequence,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Adr{}
	for rows.Next() {
		var i Adr
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.Sequence,
			&i.Title,
			&i.Status,
			&i.Context,
			&i.Decision,
			&i.Drivers,
			&i.Options,
			&i.Consequences,
			&i.CreatedBy,
			&i.AgentSessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateADRStatus = `-- name: UpdateADRStatus :one
UPDATE adrs SET status = $2, updated_at = now()
WHERE id = $1 AND tenant_id = $3
RETURNING id, tenant_id, project_id, sequence, title, status, context, decision, drivers, options, consequences, created_by, agent_session_id, created_at, updated_at
`

type UpdateADRStatusParams struct {
	ID       uuid.UUID `json:"id"`
	Status   string    `json:"status"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateADRStatus(ctx context.Context, arg UpdateADRStatusParams) (Adr, error) {
	row := q.db.QueryRow(ctx, updateADRStatus, arg.ID, arg.Status, arg.TenantID)
	var i Adr
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.Sequence,
		&i.Title,
		&i.Status,
		&i.Context,
		&i.Decision,
		&i.Drivers,
		&i.Options,
		&i.Consequences,
		&i.CreatedBy,
		&i.AgentSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
