// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_session_events.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createAgentSessionEvent = `-- name: CreateAgentSessionEvent :one
INSERT INTO agent_session_events (tenant_id, agent_session_id, event_type, payload, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, agent_session_id, event_type, payload, created_at
`

type CreateAgentSessionEventParams struct {
	TenantID       uuid.UUID       `json:"tenant_id"`
	AgentSessionID uuid.UUID       `json:"agent_session_id"`
	EventType      string          `json:"event_type"`
	Payload        json.RawMessage `json:"payload"`
	CreatedAt      time.Time       `json:"created_at"`
}

func (q *Queries) CreateAgentSessionEvent(ctx context.Context, arg CreateAgentSessionEventParams) (AgentSessionEvent, error) {
	row := q.db.QueryRow(ctx, createAgentSessionEvent,
		arg.TenantID,
		arg.AgentSessionID,
		arg.EventType,
		arg.Payload,
		arg.CreatedAt,
	)
	var i AgentSessionEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentSessionID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentSessionEventByID = `-- name: GetAgentSessionEventByID :one
SELECT id, tenant_id, agent_session_id, event_type, payload, created_at
FROM agent_session_events
WHERE id = $1 AND tenant_id = $2 AND agent_session_id = $3
`

type GetAgentSessionEventByIDParams struct {
	ID             uuid.UUID `json:"id"`
	TenantID       uuid.UUID `json:"tenant_id"`
	AgentSessionID uuid.UUID `json:"agent_session_id"`
}

func (q *Queries) GetAgentSessionEventByID(ctx context.Context, arg GetAgentSessionEventByIDParams) (AgentSessionEvent, error) {
	row := q.db.QueryRow(ctx, getAgentSessionEventByID, arg.ID, arg.TenantID, arg.AgentSessionID)
	var i AgentSessionEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentSessionID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentSessionEventsBySession = `-- name: ListAgentSessionEventsBySession :many
SELECT id, tenant_id, agent_session_id, event_type, payload, created_at
FROM agent_session_events
WHERE tenant_id = $1 AND agent_session_id = $2
ORDER BY created_at ASC, id ASC
LIMIT $3
`

type ListAgentSessionEventsBySessionParams struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	AgentSessionID uuid.UUID `json:"agent_session_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListAgentSessionEventsBySession(ctx context.Context, arg ListAgentSessionEventsBySessionParams) ([]AgentSessionEvent, error) {
	rows, err := q.db.Query(ctx, listAgentSessionEventsBySession, arg.TenantID, arg.AgentSessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentSessionEvent{}
	for rows.Next() {
		var i AgentSessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AgentSessionID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentSessionEventsBySessionAfterCursor = `-- name: ListAgentSessionEventsBySessionAfterCursor :many
SELECT id, tenant_id, agent_session_id, event_type, payload, created_at
FROM agent_session_events AS e
WHERE e.tenant_id = $1
  AND e.agent_session_id = $2
  AND (
    e.created_at > (
      SELECT cursor.created_at
      FROM agent_session_events AS cursor
      WHERE cursor.id = $3 AND cursor.tenant_id = $1 AND cursor.agent_session_id = $2
    )
    OR (
      e.created_at = (
        SELECT cursor.created_at
        FROM agent_session_events AS cursor
        WHERE cursor.id = $3 AND cursor.tenant_id = $1 AND cursor.agent_session_id = $2
      )
      AND e.id > $3
    )
  )
ORDER BY e.created_at ASC, e.id ASC
LIMIT $4
`

type ListAgentSessionEventsBySessionAfterCursorParams struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	AgentSessionID uuid.UUID `json:"agent_session_id"`
	ID             uuid.UUID `json:"id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListAgentSessionEventsBySessionAfterCursor(ctx context.Context, arg ListAgentSessionEventsBySessionAfterCursorParams) ([]AgentSessionEvent, error) {
	rows, err := q.db.Query(ctx, listAgentSessionEventsBySessionAfterCursor,
		arg.TenantID,
		arg.AgentSessionID,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentSessionEvent{}
	for rows.Next() {
		var i AgentSessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AgentSessionID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
