// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_sessions.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentSession = `-- name: CreateAgentSession :one
INSERT INTO agent_sessions (tenant_id, project_id, task_id, agent_type, status, branch_name, metadata, retry_count, retry_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, project_id, task_id, agent_type, status, container_id, branch_name, started_at, completed_at, error, metadata, retry_count, retry_at, created_at
`

type CreateAgentSessionParams struct {
	TenantID   uuid.UUID          `json:"tenant_id"`
	ProjectID  uuid.UUID          `json:"project_id"`
	TaskID     uuid.UUID          `json:"task_id"`
	AgentType  string             `json:"agent_type"`
	Status     string             `json:"status"`
	BranchName *string            `json:"branch_name"`
	Metadata   json.RawMessage    `json:"metadata"`
	RetryCount int32              `json:"retry_count"`
	RetryAt    pgtype.Timestamptz `json:"retry_at"`
}

func (q *Queries) CreateAgentSession(ctx context.Context, arg CreateAgentSessionParams) (AgentSession, error) {
	row := q.db.QueryRow(ctx, createAgentSession,
		arg.TenantID,
		arg.ProjectID,
		arg.TaskID,
		arg.AgentType,
		arg.Status,
		arg.BranchName,
		arg.Metadata,
		arg.RetryCount,
		arg.RetryAt,
	)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.TaskID,
		&i.AgentType,
		&i.Status,
		&i.ContainerID,
		&i.BranchName,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.Metadata,
		&i.RetryCount,
		&i.RetryAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentSessionByID = `-- name: GetAgentSessionByID :one
SELECT id, tenant_id, project_id, task_id, agent_type, status, container_id, branch_name, started_at, completed_at, error, metadata, retry_count, retry_at, created_at FROM agent_sessions WHERE id = $1 AND tenant_id = $2
`

type GetAgentSessionByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetAgentSessionByID(ctx context.Context, arg GetAgentSessionByIDParams) (AgentSession, error) {
	row := q.db.QueryRow(ctx, getAgentSessionByID, arg.ID, arg.TenantID)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.TaskID,
		&i.AgentType,
		&i.Status,
		&i.ContainerID,
		&i.BranchName,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.Metadata,
		&i.RetryCount,
		&i.RetryAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentSessionsByProject = `-- name: ListAgentSessionsByProject :many
SELECT id, tenant_id, project_id, task_id, agent_type, status, container_id, branch_name, started_at, completed_at, error, metadata, retry_count, retry_at, created_at FROM agent_sessions WHERE project_id = $1 AND tenant_id = $2
ORDER BY created_at DESC, id DESC
`

type ListAgentSessionsByProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	TenantID  uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListAgentSessionsByProject(ctx context.Context, arg ListAgentSessionsByProjectParams) ([]AgentSession, error) {
	rows, err := q.db.Query(ctx, listAgentSessionsByProject, arg.ProjectID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentSession{}
	for rows.Next() {
		var i AgentSession
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.TaskID,
			&i.AgentType,
			&i.Status,
			&i.ContainerID,
			&i.BranchName,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
			&i.Metadata,
			&i.RetryCount,
			&i.RetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentSessionsByTask = `-- name: ListAgentSessionsByTask :many
SELECT id, tenant_id, project_id, task_id, agent_type, status, container_id, branch_name, started_at, completed_at, error, metadata, retry_count, retry_at, created_at FROM agent_sessions WHERE task_id = $1 AND tenant_id = $2
ORDER BY created_at DESC, id DESC
`

type ListAgentSessionsByTaskParams struct {
	TaskID   uuid.UUID `json:"task_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListAgentSessionsByTask(ctx context.Context, arg ListAgentSessionsByTaskParams) ([]AgentSession, error) {
	rows, err := q.db.Query(ctx, listAgentSessionsByTask, arg.TaskID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentSession{}
	for rows.Next() {
		var i AgentSession
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.TaskID,
			&i.AgentType,
			&i.Status,
			&i.ContainerID,
			&i.BranchName,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
			&i.Metadata,
			&i.RetryCount,
			&i.RetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentSessionsRetryReady = `-- name: ListAgentSessionsRetryReady :many
SELECT id, tenant_id, project_id, task_id, agent_type, status, container_id, branch_name, started_at, completed_at, error, metadata, retry_count, retry_at, created_at FROM agent_sessions
WHERE retry_at IS NOT NULL AND retry_at <= $1
ORDER BY retry_at ASC, created_at ASC, id ASC
LIMIT $2
`

type ListAgentSessionsRetryReadyParams struct {
	RetryAt pgtype.Timestamptz `json:"retry_at"`
	Limit   int32              `json:"limit"`
}

func (q *Queries) ListAgentSessionsRetryReady(ctx context.Context, arg ListAgentSessionsRetryReadyParams) ([]AgentSession, error) {
	rows, err := q.db.Query(ctx, listAgentSessionsRetryReady, arg.RetryAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentSession{}
	for rows.Next() {
		var i AgentSession
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.TaskID,
			&i.AgentType,
			&i.Status,
			&i.ContainerID,
			&i.BranchName,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
			&i.Metadata,
			&i.RetryCount,
			&i.RetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentSessionRetry = `-- name: UpdateAgentSessionRetry :exec
UPDATE agent_sessions SET retry_count = $2, retry_at = $3
WHERE id = $1 AND tenant_id = $4
`

type UpdateAgentSessionRetryParams struct {
	ID         uuid.UUID          `json:"id"`
	RetryCount int32              `json:"retry_count"`
	RetryAt    pgtype.Timestamptz `json:"retry_at"`
	TenantID   uuid.UUID          `json:"tenant_id"`
}

func (q *Queries) UpdateAgentSessionRetry(ctx context.Context, arg UpdateAgentSessionRetryParams) error {
	_, err := q.db.Exec(ctx, updateAgentSessionRetry,
		arg.ID,
		arg.RetryCount,
		arg.RetryAt,
		arg.TenantID,
	)
	return err
}

const updateAgentSessionStatus = `-- name: UpdateAgentSessionStatus :one
UPDATE agent_sessions SET status = $2, container_id = $3, started_at = $4, completed_at = $5, error = $6
WHERE id = $1 AND tenant_id = $7
RETURNING id, tenant_id, project_id, task_id, agent_type, status, container_id, branch_name, started_at, completed_at, error, metadata, retry_count, retry_at, created_at
`

type UpdateAgentSessionStatusParams struct {
	ID          uuid.UUID          `json:"id"`
	Status      string             `json:"status"`
	ContainerID *string            `json:"container_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Error       *string            `json:"error"`
	TenantID    uuid.UUID          `json:"tenant_id"`
}

func (q *Queries) UpdateAgentSessionStatus(ctx context.Context, arg UpdateAgentSessionStatusParams) (AgentSession, error) {
	row := q.db.QueryRow(ctx, updateAgentSessionStatus,
		arg.ID,
		arg.Status,
		arg.ContainerID,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Error,
		arg.TenantID,
	)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.TaskID,
		&i.AgentType,
		&i.Status,
		&i.ContainerID,
		&i.BranchName,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.Metadata,
		&i.RetryCount,
		&i.RetryAt,
		&i.CreatedAt,
	)
	return i, err
}
