// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const appendAuditEntry = `-- name: AppendAuditEntry :one
INSERT INTO audit_log (tenant_id, actor_type, actor_id, action, resource, resource_id, details)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, actor_type, actor_id, action, resource, resource_id, details, created_at
`

type AppendAuditEntryParams struct {
	TenantID   uuid.UUID       `json:"tenant_id"`
	ActorType  string          `json:"actor_type"`
	ActorID    string          `json:"actor_id"`
	Action     string          `json:"action"`
	Resource   string          `json:"resource"`
	ResourceID string          `json:"resource_id"`
	Details    json.RawMessage `json:"details"`
}

func (q *Queries) AppendAuditEntry(ctx context.Context, arg AppendAuditEntryParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, appendAuditEntry,
		arg.TenantID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Details,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ActorType,
		&i.ActorID,
		&i.Action,
		&i.Resource,
		&i.ResourceID,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditEntryByID = `-- name: GetAuditEntryByID :one
SELECT id, tenant_id, actor_type, actor_id, action, resource, resource_id, details, created_at FROM audit_log WHERE id = $1 AND tenant_id = $2
`

type GetAuditEntryByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetAuditEntryByID(ctx context.Context, arg GetAuditEntryByIDParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditEntryByID, arg.ID, arg.TenantID)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ActorType,
		&i.ActorID,
		&i.Action,
		&i.Resource,
		&i.ResourceID,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditByResource = `-- name: ListAuditByResource :many
SELECT id, tenant_id, actor_type, actor_id, action, resource, resource_id, details, created_at FROM audit_log WHERE tenant_id = $1 AND resource = $2 AND resource_id = $3
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAuditByResourceParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	Resource   string    `json:"resource"`
	ResourceID string    `json:"resource_id"`
	Limit      int32     `json:"limit"`
}

func (q *Queries) ListAuditByResource(ctx context.Context, arg ListAuditByResourceParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByResource,
		arg.TenantID,
		arg.Resource,
		arg.ResourceID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditByResourceAfter = `-- name: ListAuditByResourceAfter :many
SELECT id, tenant_id, actor_type, actor_id, action, resource, resource_id, details, created_at FROM audit_log
WHERE tenant_id = $1 AND resource = $2 AND resource_id = $3
  AND (created_at < $4 OR (created_at = $4 AND id < $5))
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListAuditByResourceAfterParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	Resource   string    `json:"resource"`
	ResourceID string    `json:"resource_id"`
	CreatedAt  time.Time `json:"created_at"`
	ID         uuid.UUID `json:"id"`
	Limit      int32     `json:"limit"`
}

func (q *Queries) ListAuditByResourceAfter(ctx context.Context, arg ListAuditByResourceAfterParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByResourceAfter,
		arg.TenantID,
		arg.Resource,
		arg.ResourceID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditByTenant = `-- name: ListAuditByTenant :many
SELECT id, tenant_id, actor_type, actor_id, action, resource, resource_id, details, created_at FROM audit_log WHERE tenant_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListAuditByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) ListAuditByTenant(ctx context.Context, arg ListAuditByTenantParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByTenant, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditByTenantAfter = `-- name: ListAuditByTenantAfter :many
SELECT id, tenant_id, actor_type, actor_id, action, resource, resource_id, details, created_at FROM audit_log
WHERE tenant_id = $1
  AND (created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAuditByTenantAfterParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	CreatedAt time.Time `json:"created_at"`
	ID        uuid.UUID `json:"id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListAuditByTenantAfter(ctx context.Context, arg ListAuditByTenantAfterParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByTenantAfter,
		arg.TenantID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
