// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hitl_questions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const answerHITLQuestion = `-- name: AnswerHITLQuestion :one
UPDATE hitl_questions SET answer = $2, answered_by = $3, status = 'answered', answered_at = now()
WHERE id = $1 AND tenant_id = $4 AND status IN ('pending', 'escalated')
RETURNING id, tenant_id, agent_session_id, question, options, messenger_thread_id, messenger_platform, answer, answered_by, status, timeout_at, created_at, answered_at, timeout_notification_claimed_at, timeout_notified_at
`

type AnswerHITLQuestionParams struct {
	ID         uuid.UUID   `json:"id"`
	Answer     *string     `json:"answer"`
	AnsweredBy pgtype.UUID `json:"answered_by"`
	TenantID   uuid.UUID   `json:"tenant_id"`
}

func (q *Queries) AnswerHITLQuestion(ctx context.Context, arg AnswerHITLQuestionParams) (HitlQuestion, error) {
	row := q.db.QueryRow(ctx, answerHITLQuestion,
		arg.ID,
		arg.Answer,
		arg.AnsweredBy,
		arg.TenantID,
	)
	var i HitlQuestion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentSessionID,
		&i.Question,
		&i.Options,
		&i.MessengerThreadID,
		&i.MessengerPlatform,
		&i.Answer,
		&i.AnsweredBy,
		&i.Status,
		&i.TimeoutAt,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.TimeoutNotificationClaimedAt,
		&i.TimeoutNotifiedAt,
	)
	return i, err
}

const cancelPendingHITLQuestionsBySession = `-- name: CancelPendingHITLQuestionsBySession :exec
UPDATE hitl_questions
SET status = 'cancelled'
WHERE tenant_id = $1 AND agent_session_id = $2 AND status IN ('pending', 'escalated')
`

type CancelPendingHITLQuestionsBySessionParams struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	AgentSessionID uuid.UUID `json:"agent_session_id"`
}

func (q *Queries) CancelPendingHITLQuestionsBySession(ctx context.Context, arg CancelPendingHITLQuestionsBySessionParams) error {
	_, err := q.db.Exec(ctx, cancelPendingHITLQuestionsBySession, arg.TenantID, arg.AgentSessionID)
	return err
}

const claimHITLTimeoutNotification = `-- name: ClaimHITLTimeoutNotification :one
UPDATE hitl_questions
SET timeout_notification_claimed_at = now()
WHERE id = $1
  AND tenant_id = $2
  AND status = 'timeout'
  AND timeout_notified_at IS NULL
  AND (timeout_notification_claimed_at IS NULL OR timeout_notification_claimed_at < $3)
RETURNING id, tenant_id, agent_session_id, question, options, messenger_thread_id, messenger_platform, answer, answered_by, status, timeout_at, created_at, answered_at, timeout_notification_claimed_at, timeout_notified_at
`

type ClaimHITLTimeoutNotificationParams struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	StaleBefore pgtype.Timestamptz `json:"stale_before"`
}

func (q *Queries) ClaimHITLTimeoutNotification(ctx context.Context, arg ClaimHITLTimeoutNotificationParams) (HitlQuestion, error) {
	row := q.db.QueryRow(ctx, claimHITLTimeoutNotification, arg.ID, arg.TenantID, arg.StaleBefore)
	var i HitlQuestion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentSessionID,
		&i.Question,
		&i.Options,
		&i.MessengerThreadID,
		&i.MessengerPlatform,
		&i.Answer,
		&i.AnsweredBy,
		&i.Status,
		&i.TimeoutAt,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.TimeoutNotificationClaimedAt,
		&i.TimeoutNotifiedAt,
	)
	return i, err
}

const clearHITLTimeoutNotificationClaim = `-- name: ClearHITLTimeoutNotificationClaim :exec
UPDATE hitl_questions
SET timeout_notification_claimed_at = NULL
WHERE id = $1 AND tenant_id = $2 AND status = 'timeout'
`

type ClearHITLTimeoutNotificationClaimParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ClearHITLTimeoutNotificationClaim(ctx context.Context, arg ClearHITLTimeoutNotificationClaimParams) error {
	_, err := q.db.Exec(ctx, clearHITLTimeoutNotificationClaim, arg.ID, arg.TenantID)
	return err
}

const createHITLQuestion = `-- name: CreateHITLQuestion :one
INSERT INTO hitl_questions (id, tenant_id, agent_session_id, question, options, messenger_thread_id, messenger_platform, status, timeout_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, agent_session_id, question, options, messenger_thread_id, messenger_platform, answer, answered_by, status, timeout_at, created_at, answered_at, timeout_notification_claimed_at, timeout_notified_at
`

type CreateHITLQuestionParams struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	AgentSessionID    uuid.UUID          `json:"agent_session_id"`
	Question          string             `json:"question"`
	Options           []byte             `json:"options"`
	MessengerThreadID *string            `json:"messenger_thread_id"`
	MessengerPlatform *string            `json:"messenger_platform"`
	Status            string             `json:"status"`
	TimeoutAt         pgtype.Timestamptz `json:"timeout_at"`
}

func (q *Queries) CreateHITLQuestion(ctx context.Context, arg CreateHITLQuestionParams) (HitlQuestion, error) {
	row := q.db.QueryRow(ctx, createHITLQuestion,
		arg.ID,
		arg.TenantID,
		arg.AgentSessionID,
		arg.Question,
		arg.Options,
		arg.MessengerThreadID,
		arg.MessengerPlatform,
		arg.Status,
		arg.TimeoutAt,
	)
	var i HitlQuestion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentSessionID,
		&i.Question,
		&i.Options,
		&i.MessengerThreadID,
		&i.MessengerPlatform,
		&i.Answer,
		&i.AnsweredBy,
		&i.Status,
		&i.TimeoutAt,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.TimeoutNotificationClaimedAt,
		&i.TimeoutNotifiedAt,
	)
	return i, err
}

const deleteHITLQuestion = `-- name: DeleteHITLQuestion :exec
DELETE FROM hitl_questions WHERE id = $1 AND tenant_id = $2
`

type DeleteHITLQuestionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteHITLQuestion(ctx context.Context, arg DeleteHITLQuestionParams) error {
	_, err := q.db.Exec(ctx, deleteHITLQuestion, arg.ID, arg.TenantID)
	return err
}

const escalateHITLQuestion = `-- name: EscalateHITLQuestion :one
UPDATE hitl_questions
SET status = 'escalated', timeout_at = $2
WHERE id = $1 AND tenant_id = $3 AND status = 'pending'
RETURNING id, tenant_id, agent_session_id, question, options, messenger_thread_id, messenger_platform, answer, answered_by, status, timeout_at, created_at, answered_at, timeout_notification_claimed_at, timeout_notified_at
`

type EscalateHITLQuestionParams struct {
	ID           uuid.UUID          `json:"id"`
	NewTimeoutAt pgtype.Timestamptz `json:"new_timeout_at"`
	TenantID     uuid.UUID          `json:"tenant_id"`
}

func (q *Queries) EscalateHITLQuestion(ctx context.Context, arg EscalateHITLQuestionParams) (HitlQuestion, error) {
	row := q.db.QueryRow(ctx, escalateHITLQuestion, arg.ID, arg.NewTimeoutAt, arg.TenantID)
	var i HitlQuestion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentSessionID,
		&i.Question,
		&i.Options,
		&i.MessengerThreadID,
		&i.MessengerPlatform,
		&i.Answer,
		&i.AnsweredBy,
		&i.Status,
		&i.TimeoutAt,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.TimeoutNotificationClaimedAt,
		&i.TimeoutNotifiedAt,
	)
	return i, err
}

const getHITLQuestionByID = `-- name: GetHITLQuestionByID :one
SELECT id, tenant_id, agent_session_id, question, options, messenger_thread_id, messenger_platform, answer, answered_by, status, timeout_at, created_at, answered_at, timeout_notification_claimed_at, timeout_notified_at FROM hitl_questions WHERE id = $1 AND tenant_id = $2
`

type GetHITLQuestionByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetHITLQuestionByID(ctx context.Context, arg GetHITLQuestionByIDParams) (HitlQuestion, error) {
	row := q.db.QueryRow(ctx, getHITLQuestionByID, arg.ID, arg.TenantID)
	var i HitlQuestion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentSessionID,
		&i.Question,
		&i.Options,
		&i.MessengerThreadID,
		&i.MessengerPlatform,
		&i.Answer,
		&i.AnsweredBy,
		&i.Status,
		&i.TimeoutAt,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.TimeoutNotificationClaimedAt,
		&i.TimeoutNotifiedAt,
	)
	return i, err
}

const getPendingHITLQuestionByThread = `-- name: GetPendingHITLQuestionByThread :many
SELECT id, tenant_id, agent_session_id, question, options, messenger_thread_id, messenger_platform, answer, answered_by, status, timeout_at, created_at, answered_at, timeout_notification_claimed_at, timeout_notified_at FROM hitl_questions
WHERE tenant_id = $1 AND messenger_platform = $2 AND messenger_thread_id = $3 AND status = 'pending'
ORDER BY created_at DESC, id DESC
LIMIT 2
`

type GetPendingHITLQuestionByThreadParams struct {
	TenantID          uuid.UUID `json:"tenant_id"`
	MessengerPlatform *string   `json:"messenger_platform"`
	MessengerThreadID *string   `json:"messenger_thread_id"`
}

func (q *Queries) GetPendingHITLQuestionByThread(ctx context.Context, arg GetPendingHITLQuestionByThreadParams) ([]HitlQuestion, error) {
	rows, err := q.db.Query(ctx, getPendingHITLQuestionByThread, arg.TenantID, arg.MessengerPlatform, arg.MessengerThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HitlQuestion{}
	for rows.Next() {
		var i HitlQuestion
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AgentSessionID,
			&i.Question,
			&i.Options,
			&i.MessengerThreadID,
			&i.MessengerPlatform,
			&i.Answer,
			&i.AnsweredBy,
			&i.Status,
			&i.TimeoutAt,
			&i.CreatedAt,
			&i.AnsweredAt,
			&i.TimeoutNotificationClaimedAt,
			&i.TimeoutNotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEscalatedExpiredHITLQuestionsBefore = `-- name: ListEscalatedExpiredHITLQuestionsBefore :many
SELECT q.id, q.tenant_id, q.agent_session_id, q.question, q.options, q.messenger_thread_id, q.messenger_platform, q.answer, q.answered_by, q.status, q.timeout_at, q.created_at, q.answered_at, q.timeout_notification_claimed_at, q.timeout_notified_at FROM hitl_questions AS q
JOIN agent_sessions AS s ON s.id = q.agent_session_id AND s.tenant_id = q.tenant_id
WHERE q.status = 'escalated' AND q.timeout_at <= $1 AND s.status IN ('pending', 'running', 'waiting_hitl')
ORDER BY q.timeout_at ASC, q.created_at ASC, q.id ASC
LIMIT $2
`

type ListEscalatedExpiredHITLQuestionsBeforeParams struct {
	TimeoutAt pgtype.Timestamptz `json:"timeout_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListEscalatedExpiredHITLQuestionsBefore(ctx context.Context, arg ListEscalatedExpiredHITLQuestionsBeforeParams) ([]HitlQuestion, error) {
	rows, err := q.db.Query(ctx, listEscalatedExpiredHITLQuestionsBefore, arg.TimeoutAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HitlQuestion{}
	for rows.Next() {
		var i HitlQuestion
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AgentSessionID,
			&i.Question,
			&i.Options,
			&i.MessengerThreadID,
			&i.MessengerPlatform,
			&i.Answer,
			&i.AnsweredBy,
			&i.Status,
			&i.TimeoutAt,
			&i.CreatedAt,
			&i.AnsweredAt,
			&i.TimeoutNotificationClaimedAt,
			&i.TimeoutNotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredPendingHITLQuestionsBefore = `-- name: ListExpiredPendingHITLQuestionsBefore :many
SELECT q.id, q.tenant_id, q.agent_session_id, q.question, q.options, q.messenger_thread_id, q.messenger_platform, q.answer, q.answered_by, q.status, q.timeout_at, q.created_at, q.answered_at, q.timeout_notification_claimed_at, q.timeout_notified_at FROM hitl_questions AS q
JOIN agent_sessions AS s ON s.id = q.agent_session_id AND s.tenant_id = q.tenant_id
WHERE q.status = 'pending' AND q.timeout_at <= $1 AND s.status IN ('pending', 'running', 'waiting_hitl', 'cancelled')
ORDER BY q.timeout_at ASC, q.created_at ASC, q.id ASC
LIMIT $2
`

type ListExpiredPendingHITLQuestionsBeforeParams struct {
	TimeoutAt pgtype.Timestamptz `json:"timeout_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListExpiredPendingHITLQuestionsBefore(ctx context.Context, arg ListExpiredPendingHITLQuestionsBeforeParams) ([]HitlQuestion, error) {
	rows, err := q.db.Query(ctx, listExpiredPendingHITLQuestionsBefore, arg.TimeoutAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HitlQuestion{}
	for rows.Next() {
		var i HitlQuestion
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AgentSessionID,
			&i.Question,
			&i.Options,
			&i.MessengerThreadID,
			&i.MessengerPlatform,
			&i.Answer,
			&i.AnsweredBy,
			&i.Status,
			&i.TimeoutAt,
			&i.CreatedAt,
			&i.AnsweredAt,
			&i.TimeoutNotificationClaimedAt,
			&i.TimeoutNotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHITLQuestionsBySession = `-- name: ListHITLQuestionsBySession :many
SELECT id, tenant_id, agent_session_id, question, options, messenger_thread_id, messenger_platform, answer, answered_by, status, timeout_at, created_at, answered_at, timeout_notification_claimed_at, timeout_notified_at FROM hitl_questions WHERE agent_session_id = $1 AND tenant_id = $2
ORDER BY created_at DESC, id DESC
`

type ListHITLQuestionsBySessionParams struct {
	AgentSessionID uuid.UUID `json:"agent_session_id"`
	TenantID       uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListHITLQuestionsBySession(ctx context.Context, arg ListHITLQuestionsBySessionParams) ([]HitlQuestion, error) {
	rows, err := q.db.Query(ctx, listHITLQuestionsBySession, arg.AgentSessionID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HitlQuestion{}
	for rows.Next() {
		var i HitlQuestion
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AgentSessionID,
			&i.Question,
			&i.Options,
			&i.MessengerThreadID,
			&i.MessengerPlatform,
			&i.Answer,
			&i.AnsweredBy,
			&i.Status,
			&i.TimeoutAt,
			&i.CreatedAt,
			&i.AnsweredAt,
			&i.TimeoutNotificationClaimedAt,
			&i.TimeoutNotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimedOutHITLQuestions = `-- name: ListTimedOutHITLQuestions :many
SELECT q.id, q.tenant_id, q.agent_session_id, q.question, q.options, q.messenger_thread_id, q.messenger_platform, q.answer, q.answered_by, q.status, q.timeout_at, q.created_at, q.answered_at, q.timeout_notification_claimed_at, q.timeout_notified_at FROM hitl_questions AS q
JOIN agent_sessions AS s ON s.id = q.agent_session_id AND s.tenant_id = q.tenant_id
WHERE q.status = 'timeout' AND s.status IN ('pending', 'running', 'waiting_hitl')
ORDER BY q.timeout_at ASC, q.created_at ASC, q.id ASC
LIMIT $1
`

func (q *Queries) ListTimedOutHITLQuestions(ctx context.Context, limit int32) ([]HitlQuestion, error) {
	rows, err := q.db.Query(ctx, listTimedOutHITLQuestions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HitlQuestion{}
	for rows.Next() {
		var i HitlQuestion
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AgentSessionID,
			&i.Question,
			&i.Options,
			&i.MessengerThreadID,
			&i.MessengerPlatform,
			&i.Answer,
			&i.AnsweredBy,
			&i.Status,
			&i.TimeoutAt,
			&i.CreatedAt,
			&i.AnsweredAt,
			&i.TimeoutNotificationClaimedAt,
			&i.TimeoutNotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnnotifiedTimedOutHITLQuestions = `-- name: ListUnnotifiedTimedOutHITLQuestions :many
SELECT q.id, q.tenant_id, q.agent_session_id, q.question, q.options, q.messenger_thread_id, q.messenger_platform, q.answer, q.answered_by, q.status, q.timeout_at, q.created_at, q.answered_at, q.timeout_notification_claimed_at, q.timeout_notified_at
FROM hitl_questions AS q
JOIN agent_sessions AS s ON s.id = q.agent_session_id AND s.tenant_id = q.tenant_id
WHERE q.status = 'timeout'
  AND q.timeout_notified_at IS NULL
  AND s.status IN ('cancelled', 'completed', 'failed')
  AND (q.timeout_notification_claimed_at IS NULL OR q.timeout_notification_claimed_at < $1)
ORDER BY q.timeout_at ASC, q.created_at ASC, q.id ASC
LIMIT $2
`

type ListUnnotifiedTimedOutHITLQuestionsParams struct {
	TimeoutNotificationClaimedAt pgtype.Timestamptz `json:"timeout_notification_claimed_at"`
	Limit                        int32              `json:"limit"`
}

func (q *Queries) ListUnnotifiedTimedOutHITLQuestions(ctx context.Context, arg ListUnnotifiedTimedOutHITLQuestionsParams) ([]HitlQuestion, error) {
	rows, err := q.db.Query(ctx, listUnnotifiedTimedOutHITLQuestions, arg.TimeoutNotificationClaimedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HitlQuestion{}
	for rows.Next() {
		var i HitlQuestion
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AgentSessionID,
			&i.Question,
			&i.Options,
			&i.MessengerThreadID,
			&i.MessengerPlatform,
			&i.Answer,
			&i.AnsweredBy,
			&i.Status,
			&i.TimeoutAt,
			&i.CreatedAt,
			&i.AnsweredAt,
			&i.TimeoutNotificationClaimedAt,
			&i.TimeoutNotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markHITLTimeoutNotificationSent = `-- name: MarkHITLTimeoutNotificationSent :one
UPDATE hitl_questions
SET timeout_notification_claimed_at = NULL, timeout_notified_at = now()
WHERE id = $1 AND tenant_id = $2 AND status = 'timeout' AND timeout_notified_at IS NULL
RETURNING id, tenant_id, agent_session_id, question, options, messenger_thread_id, messenger_platform, answer, answered_by, status, timeout_at, created_at, answered_at, timeout_notification_claimed_at, timeout_notified_at
`

type MarkHITLTimeoutNotificationSentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) MarkHITLTimeoutNotificationSent(ctx context.Context, arg MarkHITLTimeoutNotificationSentParams) (HitlQuestion, error) {
	row := q.db.QueryRow(ctx, markHITLTimeoutNotificationSent, arg.ID, arg.TenantID)
	var i HitlQuestion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentSessionID,
		&i.Question,
		&i.Options,
		&i.MessengerThreadID,
		&i.MessengerPlatform,
		&i.Answer,
		&i.AnsweredBy,
		&i.Status,
		&i.TimeoutAt,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.TimeoutNotificationClaimedAt,
		&i.TimeoutNotifiedAt,
	)
	return i, err
}

const markTimedOutEscalatedHITLQuestion = `-- name: MarkTimedOutEscalatedHITLQuestion :one
UPDATE hitl_questions SET status = 'timeout'
WHERE id = $1 AND tenant_id = $2 AND status = 'escalated'
RETURNING id, tenant_id, agent_session_id, question, options, messenger_thread_id, messenger_platform, answer, answered_by, status, timeout_at, created_at, answered_at, timeout_notification_claimed_at, timeout_notified_at
`

type MarkTimedOutEscalatedHITLQuestionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) MarkTimedOutEscalatedHITLQuestion(ctx context.Context, arg MarkTimedOutEscalatedHITLQuestionParams) (HitlQuestion, error) {
	row := q.db.QueryRow(ctx, markTimedOutEscalatedHITLQuestion, arg.ID, arg.TenantID)
	var i HitlQuestion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentSessionID,
		&i.Question,
		&i.Options,
		&i.MessengerThreadID,
		&i.MessengerPlatform,
		&i.Answer,
		&i.AnsweredBy,
		&i.Status,
		&i.TimeoutAt,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.TimeoutNotificationClaimedAt,
		&i.TimeoutNotifiedAt,
	)
	return i, err
}

const markTimedOutHITLQuestion = `-- name: MarkTimedOutHITLQuestion :one
UPDATE hitl_questions SET status = 'timeout'
WHERE id = $1 AND tenant_id = $2 AND status = 'pending'
RETURNING id, tenant_id, agent_session_id, question, options, messenger_thread_id, messenger_platform, answer, answered_by, status, timeout_at, created_at, answered_at, timeout_notification_claimed_at, timeout_notified_at
`

type MarkTimedOutHITLQuestionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) MarkTimedOutHITLQuestion(ctx context.Context, arg MarkTimedOutHITLQuestionParams) (HitlQuestion, error) {
	row := q.db.QueryRow(ctx, markTimedOutHITLQuestion, arg.ID, arg.TenantID)
	var i HitlQuestion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentSessionID,
		&i.Question,
		&i.Options,
		&i.MessengerThreadID,
		&i.MessengerPlatform,
		&i.Answer,
		&i.AnsweredBy,
		&i.Status,
		&i.TimeoutAt,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.TimeoutNotificationClaimedAt,
		&i.TimeoutNotifiedAt,
	)
	return i, err
}

const markTimedOutHITLQuestionsBefore = `-- name: MarkTimedOutHITLQuestionsBefore :many
WITH expired AS (
    SELECT id
    FROM hitl_questions AS h
    WHERE h.status = 'pending' AND h.timeout_at <= $1
    ORDER BY h.timeout_at ASC, h.created_at ASC, h.id ASC
    LIMIT $2
)
UPDATE hitl_questions AS q
SET status = 'timeout'
FROM expired
WHERE q.id = expired.id
RETURNING q.id, q.tenant_id, q.agent_session_id, q.question, q.options, q.messenger_thread_id, q.messenger_platform, q.answer, q.answered_by, q.status, q.timeout_at, q.created_at, q.answered_at, q.timeout_notification_claimed_at, q.timeout_notified_at
`

type MarkTimedOutHITLQuestionsBeforeParams struct {
	TimeoutAt pgtype.Timestamptz `json:"timeout_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) MarkTimedOutHITLQuestionsBefore(ctx context.Context, arg MarkTimedOutHITLQuestionsBeforeParams) ([]HitlQuestion, error) {
	rows, err := q.db.Query(ctx, markTimedOutHITLQuestionsBefore, arg.TimeoutAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HitlQuestion{}
	for rows.Next() {
		var i HitlQuestion
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AgentSessionID,
			&i.Question,
			&i.Options,
			&i.MessengerThreadID,
			&i.MessengerPlatform,
			&i.Answer,
			&i.AnsweredBy,
			&i.Status,
			&i.TimeoutAt,
			&i.CreatedAt,
			&i.AnsweredAt,
			&i.TimeoutNotificationClaimedAt,
			&i.TimeoutNotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenTimedOutHITLQuestion = `-- name: ReopenTimedOutHITLQuestion :one
UPDATE hitl_questions
SET status = 'pending', timeout_notification_claimed_at = NULL, timeout_notified_at = NULL
WHERE id = $1 AND tenant_id = $2 AND status = 'timeout'
RETURNING id, tenant_id, agent_session_id, question, options, messenger_thread_id, messenger_platform, answer, answered_by, status, timeout_at, created_at, answered_at, timeout_notification_claimed_at, timeout_notified_at
`

type ReopenTimedOutHITLQuestionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ReopenTimedOutHITLQuestion(ctx context.Context, arg ReopenTimedOutHITLQuestionParams) (HitlQuestion, error) {
	row := q.db.QueryRow(ctx, reopenTimedOutHITLQuestion, arg.ID, arg.TenantID)
	var i HitlQuestion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentSessionID,
		&i.Question,
		&i.Options,
		&i.MessengerThreadID,
		&i.MessengerPlatform,
		&i.Answer,
		&i.AnsweredBy,
		&i.Status,
		&i.TimeoutAt,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.TimeoutNotificationClaimedAt,
		&i.TimeoutNotifiedAt,
	)
	return i, err
}

const resetHITLQuestionAnswer = `-- name: ResetHITLQuestionAnswer :one
UPDATE hitl_questions SET answer = NULL, answered_by = NULL, status = 'pending', answered_at = NULL
WHERE id = $1 AND tenant_id = $2 AND status = 'answered'
RETURNING id, tenant_id, agent_session_id, question, options, messenger_thread_id, messenger_platform, answer, answered_by, status, timeout_at, created_at, answered_at, timeout_notification_claimed_at, timeout_notified_at
`

type ResetHITLQuestionAnswerParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ResetHITLQuestionAnswer(ctx context.Context, arg ResetHITLQuestionAnswerParams) (HitlQuestion, error) {
	row := q.db.QueryRow(ctx, resetHITLQuestionAnswer, arg.ID, arg.TenantID)
	var i HitlQuestion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentSessionID,
		&i.Question,
		&i.Options,
		&i.MessengerThreadID,
		&i.MessengerPlatform,
		&i.Answer,
		&i.AnsweredBy,
		&i.Status,
		&i.TimeoutAt,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.TimeoutNotificationClaimedAt,
		&i.TimeoutNotifiedAt,
	)
	return i, err
}

const updateHITLQuestionMessengerThread = `-- name: UpdateHITLQuestionMessengerThread :one
UPDATE hitl_questions
SET messenger_platform = $3, messenger_thread_id = $4
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, agent_session_id, question, options, messenger_thread_id, messenger_platform, answer, answered_by, status, timeout_at, created_at, answered_at, timeout_notification_claimed_at, timeout_notified_at
`

type UpdateHITLQuestionMessengerThreadParams struct {
	ID                uuid.UUID `json:"id"`
	TenantID          uuid.UUID `json:"tenant_id"`
	MessengerPlatform *string   `json:"messenger_platform"`
	MessengerThreadID *string   `json:"messenger_thread_id"`
}

func (q *Queries) UpdateHITLQuestionMessengerThread(ctx context.Context, arg UpdateHITLQuestionMessengerThreadParams) (HitlQuestion, error) {
	row := q.db.QueryRow(ctx, updateHITLQuestionMessengerThread,
		arg.ID,
		arg.TenantID,
		arg.MessengerPlatform,
		arg.MessengerThreadID,
	)
	var i HitlQuestion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AgentSessionID,
		&i.Question,
		&i.Options,
		&i.MessengerThreadID,
		&i.MessengerPlatform,
		&i.Answer,
		&i.AnsweredBy,
		&i.Status,
		&i.TimeoutAt,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.TimeoutNotificationClaimedAt,
		&i.TimeoutNotifiedAt,
	)
	return i, err
}
