// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messenger_connections.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createMessengerConnection = `-- name: CreateMessengerConnection :one
INSERT INTO messenger_connections (tenant_id, platform, config, channel_id, active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, platform, config, channel_id, active, created_at
`

type CreateMessengerConnectionParams struct {
	TenantID  uuid.UUID       `json:"tenant_id"`
	Platform  string          `json:"platform"`
	Config    json.RawMessage `json:"config"`
	ChannelID *string         `json:"channel_id"`
	Active    bool            `json:"active"`
}

func (q *Queries) CreateMessengerConnection(ctx context.Context, arg CreateMessengerConnectionParams) (MessengerConnection, error) {
	row := q.db.QueryRow(ctx, createMessengerConnection,
		arg.TenantID,
		arg.Platform,
		arg.Config,
		arg.ChannelID,
		arg.Active,
	)
	var i MessengerConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Platform,
		&i.Config,
		&i.ChannelID,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getMessengerConnection = `-- name: GetMessengerConnection :one
SELECT id, tenant_id, platform, config, channel_id, active, created_at FROM messenger_connections WHERE tenant_id = $1 AND platform = $2
`

type GetMessengerConnectionParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Platform string    `json:"platform"`
}

func (q *Queries) GetMessengerConnection(ctx context.Context, arg GetMessengerConnectionParams) (MessengerConnection, error) {
	row := q.db.QueryRow(ctx, getMessengerConnection, arg.TenantID, arg.Platform)
	var i MessengerConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Platform,
		&i.Config,
		&i.ChannelID,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getMessengerConnectionByChannel = `-- name: GetMessengerConnectionByChannel :one
SELECT id, tenant_id, platform, config, channel_id, active, created_at FROM messenger_connections
WHERE platform = $1 AND channel_id = $2 AND active = true
`

type GetMessengerConnectionByChannelParams struct {
	Platform  string  `json:"platform"`
	ChannelID *string `json:"channel_id"`
}

func (q *Queries) GetMessengerConnectionByChannel(ctx context.Context, arg GetMessengerConnectionByChannelParams) (MessengerConnection, error) {
	row := q.db.QueryRow(ctx, getMessengerConnectionByChannel, arg.Platform, arg.ChannelID)
	var i MessengerConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Platform,
		&i.Config,
		&i.ChannelID,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listMessengerConnectionsByTenant = `-- name: ListMessengerConnectionsByTenant :many
SELECT id, tenant_id, platform, config, channel_id, active, created_at FROM messenger_connections WHERE tenant_id = $1
`

func (q *Queries) ListMessengerConnectionsByTenant(ctx context.Context, tenantID uuid.UUID) ([]MessengerConnection, error) {
	rows, err := q.db.Query(ctx, listMessengerConnectionsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessengerConnection{}
	for rows.Next() {
		var i MessengerConnection
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Platform,
			&i.Config,
			&i.ChannelID,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessengerConnection = `-- name: UpdateMessengerConnection :one
UPDATE messenger_connections SET config = $3, channel_id = $4, active = $5
WHERE tenant_id = $1 AND platform = $2
RETURNING id, tenant_id, platform, config, channel_id, active, created_at
`

type UpdateMessengerConnectionParams struct {
	TenantID  uuid.UUID       `json:"tenant_id"`
	Platform  string          `json:"platform"`
	Config    json.RawMessage `json:"config"`
	ChannelID *string         `json:"channel_id"`
	Active    bool            `json:"active"`
}

func (q *Queries) UpdateMessengerConnection(ctx context.Context, arg UpdateMessengerConnectionParams) (MessengerConnection, error) {
	row := q.db.QueryRow(ctx, updateMessengerConnection,
		arg.TenantID,
		arg.Platform,
		arg.Config,
		arg.ChannelID,
		arg.Active,
	)
	var i MessengerConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Platform,
		&i.Config,
		&i.ChannelID,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
