// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Adr struct {
	ID             uuid.UUID       `json:"id"`
	TenantID       uuid.UUID       `json:"tenant_id"`
	ProjectID      uuid.UUID       `json:"project_id"`
	Sequence       int32           `json:"sequence"`
	Title          string          `json:"title"`
	Status         string          `json:"status"`
	Context        string          `json:"context"`
	Decision       string          `json:"decision"`
	Drivers        []string        `json:"drivers"`
	Options        json.RawMessage `json:"options"`
	Consequences   json.RawMessage `json:"consequences"`
	CreatedBy      pgtype.UUID     `json:"created_by"`
	AgentSessionID pgtype.UUID     `json:"agent_session_id"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type AgentSession struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	TaskID      uuid.UUID          `json:"task_id"`
	AgentType   string             `json:"agent_type"`
	Status      string             `json:"status"`
	ContainerID *string            `json:"container_id"`
	BranchName  *string            `json:"branch_name"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Error       *string            `json:"error"`
	Metadata    json.RawMessage    `json:"metadata"`
	RetryCount  int32              `json:"retry_count"`
	RetryAt     pgtype.Timestamptz `json:"retry_at"`
	CreatedAt   time.Time          `json:"created_at"`
}

type AgentSessionEvent struct {
	ID             uuid.UUID       `json:"id"`
	TenantID       uuid.UUID       `json:"tenant_id"`
	AgentSessionID uuid.UUID       `json:"agent_session_id"`
	EventType      string          `json:"event_type"`
	Payload        json.RawMessage `json:"payload"`
	CreatedAt      time.Time       `json:"created_at"`
}

type ApiKey struct {
	ID         uuid.UUID          `json:"id"`
	TenantID   uuid.UUID          `json:"tenant_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	Prefix     string             `json:"prefix"`
	Scopes     []string           `json:"scopes"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type AuditLog struct {
	ID         uuid.UUID       `json:"id"`
	TenantID   uuid.UUID       `json:"tenant_id"`
	ActorType  string          `json:"actor_type"`
	ActorID    string          `json:"actor_id"`
	Action     string          `json:"action"`
	Resource   string          `json:"resource"`
	ResourceID string          `json:"resource_id"`
	Details    json.RawMessage `json:"details"`
	CreatedAt  time.Time       `json:"created_at"`
}

type HitlQuestion struct {
	ID                           uuid.UUID          `json:"id"`
	TenantID                     uuid.UUID          `json:"tenant_id"`
	AgentSessionID               uuid.UUID          `json:"agent_session_id"`
	Question                     string             `json:"question"`
	Options                      []byte             `json:"options"`
	MessengerThreadID            *string            `json:"messenger_thread_id"`
	MessengerPlatform            *string            `json:"messenger_platform"`
	Answer                       *string            `json:"answer"`
	AnsweredBy                   pgtype.UUID        `json:"answered_by"`
	Status                       string             `json:"status"`
	TimeoutAt                    pgtype.Timestamptz `json:"timeout_at"`
	CreatedAt                    time.Time          `json:"created_at"`
	AnsweredAt                   pgtype.Timestamptz `json:"answered_at"`
	TimeoutNotificationClaimedAt pgtype.Timestamptz `json:"timeout_notification_claimed_at"`
	TimeoutNotifiedAt            pgtype.Timestamptz `json:"timeout_notified_at"`
}

type MessengerConnection struct {
	ID        uuid.UUID       `json:"id"`
	TenantID  uuid.UUID       `json:"tenant_id"`
	Platform  string          `json:"platform"`
	Config    json.RawMessage `json:"config"`
	ChannelID *string         `json:"channel_id"`
	Active    bool            `json:"active"`
	CreatedAt time.Time       `json:"created_at"`
}

type Project struct {
	ID        uuid.UUID       `json:"id"`
	TenantID  uuid.UUID       `json:"tenant_id"`
	Name      string          `json:"name"`
	RepoUrl   string          `json:"repo_url"`
	Branch    string          `json:"branch"`
	Settings  json.RawMessage `json:"settings"`
	CreatedAt time.Time       `json:"created_at"`
}

type RepoVolume struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	VolumeName    string             `json:"volume_name"`
	LastFetchedAt pgtype.Timestamptz `json:"last_fetched_at"`
	SizeBytes     int64              `json:"size_bytes"`
	CreatedAt     time.Time          `json:"created_at"`
}

type Task struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       uuid.UUID   `json:"tenant_id"`
	ProjectID      uuid.UUID   `json:"project_id"`
	AdrID          pgtype.UUID `json:"adr_id"`
	Title          string      `json:"title"`
	Description    string      `json:"description"`
	Status         string      `json:"status"`
	Priority       int32       `json:"priority"`
	AssignedTo     pgtype.UUID `json:"assigned_to"`
	AgentSessionID pgtype.UUID `json:"agent_session_id"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type Tenant struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Slug      string          `json:"slug"`
	Settings  json.RawMessage `json:"settings"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Email        *string   `json:"email"`
	PasswordHash *string   `json:"password_hash"`
	Name         string    `json:"name"`
	Role         string    `json:"role"`
	AvatarUrl    *string   `json:"avatar_url"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type UserMessengerLink struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Platform   string    `json:"platform"`
	ExternalID string    `json:"external_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type UserOauthLink struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	Provider     string    `json:"provider"`
	ProviderID   string    `json:"provider_id"`
	AccessToken  *string   `json:"access_token"`
	RefreshToken *string   `json:"refresh_token"`
	CreatedAt    time.Time `json:"created_at"`
}
