// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (tenant_id, name, repo_url, branch, settings)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, repo_url, branch, settings, created_at
`

type CreateProjectParams struct {
	TenantID uuid.UUID       `json:"tenant_id"`
	Name     string          `json:"name"`
	RepoUrl  string          `json:"repo_url"`
	Branch   string          `json:"branch"`
	Settings json.RawMessage `json:"settings"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.TenantID,
		arg.Name,
		arg.RepoUrl,
		arg.Branch,
		arg.Settings,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.RepoUrl,
		&i.Branch,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE id = $1 AND tenant_id = $2
`

type DeleteProjectParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, tenant_id, name, repo_url, branch, settings, created_at FROM projects WHERE id = $1 AND tenant_id = $2
`

type GetProjectByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.ID, arg.TenantID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.RepoUrl,
		&i.Branch,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectsByTenant = `-- name: ListProjectsByTenant :many
SELECT id, tenant_id, name, repo_url, branch, settings, created_at FROM projects WHERE tenant_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListProjectsByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) ListProjectsByTenant(ctx context.Context, arg ListProjectsByTenantParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByTenant, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.RepoUrl,
			&i.Branch,
			&i.Settings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByTenantAfter = `-- name: ListProjectsByTenantAfter :many
SELECT id, tenant_id, name, repo_url, branch, settings, created_at FROM projects
WHERE tenant_id = $1
  AND (created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListProjectsByTenantAfterParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	CreatedAt time.Time `json:"created_at"`
	ID        uuid.UUID `json:"id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListProjectsByTenantAfter(ctx context.Context, arg ListProjectsByTenantAfterParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByTenantAfter,
		arg.TenantID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.RepoUrl,
			&i.Branch,
			&i.Settings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProjectForUpdate = `-- name: LockProjectForUpdate :one
SELECT id, tenant_id, name, repo_url, branch, settings, created_at FROM projects WHERE id = $1 AND tenant_id = $2 FOR UPDATE
`

type LockProjectForUpdateParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) LockProjectForUpdate(ctx context.Context, arg LockProjectForUpdateParams) (Project, error) {
	row := q.db.QueryRow(ctx, lockProjectForUpdate, arg.ID, arg.TenantID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.RepoUrl,
		&i.Branch,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET name = $2, repo_url = $3, branch = $4, settings = $5
WHERE id = $1 AND tenant_id = $6
RETURNING id, tenant_id, name, repo_url, branch, settings, created_at
`

type UpdateProjectParams struct {
	ID       uuid.UUID       `json:"id"`
	Name     string          `json:"name"`
	RepoUrl  string          `json:"repo_url"`
	Branch   string          `json:"branch"`
	Settings json.RawMessage `json:"settings"`
	TenantID uuid.UUID       `json:"tenant_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.RepoUrl,
		arg.Branch,
		arg.Settings,
		arg.TenantID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.RepoUrl,
		&i.Branch,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}
