// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repo_volumes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createRepoVolume = `-- name: CreateRepoVolume :one
INSERT INTO repo_volumes (project_id, volume_name)
VALUES ($1, $2)
RETURNING id, project_id, volume_name, last_fetched_at, size_bytes, created_at
`

type CreateRepoVolumeParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	VolumeName string    `json:"volume_name"`
}

func (q *Queries) CreateRepoVolume(ctx context.Context, arg CreateRepoVolumeParams) (RepoVolume, error) {
	row := q.db.QueryRow(ctx, createRepoVolume, arg.ProjectID, arg.VolumeName)
	var i RepoVolume
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.VolumeName,
		&i.LastFetchedAt,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRepoVolume = `-- name: DeleteRepoVolume :exec
DELETE FROM repo_volumes WHERE project_id = $1
`

func (q *Queries) DeleteRepoVolume(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRepoVolume, projectID)
	return err
}

const getRepoVolumeByProject = `-- name: GetRepoVolumeByProject :one
SELECT id, project_id, volume_name, last_fetched_at, size_bytes, created_at FROM repo_volumes WHERE project_id = $1
`

func (q *Queries) GetRepoVolumeByProject(ctx context.Context, projectID uuid.UUID) (RepoVolume, error) {
	row := q.db.QueryRow(ctx, getRepoVolumeByProject, projectID)
	var i RepoVolume
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.VolumeName,
		&i.LastFetchedAt,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const updateRepoVolumeLastFetched = `-- name: UpdateRepoVolumeLastFetched :exec
UPDATE repo_volumes SET last_fetched_at = now(), size_bytes = $2 WHERE project_id = $1
`

type UpdateRepoVolumeLastFetchedParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	SizeBytes int64     `json:"size_bytes"`
}

func (q *Queries) UpdateRepoVolumeLastFetched(ctx context.Context, arg UpdateRepoVolumeLastFetchedParams) error {
	_, err := q.db.Exec(ctx, updateRepoVolumeLastFetched, arg.ProjectID, arg.SizeBytes)
	return err
}
