// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (tenant_id, project_id, adr_id, title, description, status, priority, assigned_to)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, project_id, adr_id, title, description, status, priority, assigned_to, agent_session_id, created_at, updated_at
`

type CreateTaskParams struct {
	TenantID    uuid.UUID   `json:"tenant_id"`
	ProjectID   uuid.UUID   `json:"project_id"`
	AdrID       pgtype.UUID `json:"adr_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Status      string      `json:"status"`
	Priority    int32       `json:"priority"`
	AssignedTo  pgtype.UUID `json:"assigned_to"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.TenantID,
		arg.ProjectID,
		arg.AdrID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssignedTo,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.AdrID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedTo,
		&i.AgentSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks WHERE id = $1 AND tenant_id = $2
`

type DeleteTaskParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, tenant_id, project_id, adr_id, title, description, status, priority, assigned_to, agent_session_id, created_at, updated_at FROM tasks WHERE id = $1 AND tenant_id = $2
`

type GetTaskByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID, arg.TenantID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.AdrID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedTo,
		&i.AgentSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, tenant_id, project_id, adr_id, title, description, status, priority, assigned_to, agent_session_id, created_at, updated_at FROM tasks
WHERE project_id = $1
  AND tenant_id = $2
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::int IS NULL OR priority = $4::int)
ORDER BY priority ASC, created_at DESC, id DESC
LIMIT $5
`

type ListTasksByProjectParams struct {
	ProjectID      uuid.UUID `json:"project_id"`
	TenantID       uuid.UUID `json:"tenant_id"`
	FilterStatus   *string   `json:"filter_status"`
	FilterPriority *int32    `json:"filter_priority"`
	LimitCount     int32     `json:"limit_count"`
}

func (q *Queries) ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByProject,
		arg.ProjectID,
		arg.TenantID,
		arg.FilterStatus,
		arg.FilterPriority,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.AdrID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssignedTo,
			&i.AgentSessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProjectAfter = `-- name: ListTasksByProjectAfter :many
SELECT id, tenant_id, project_id, adr_id, title, description, status, priority, assigned_to, agent_session_id, created_at, updated_at FROM tasks
WHERE project_id = $1
  AND tenant_id = $2
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::int IS NULL OR priority = $4::int)
  AND (
    priority > $5
    OR (priority = $5 AND created_at < $6)
    OR (priority = $5 AND created_at = $6 AND id < $7)
  )
ORDER BY priority ASC, created_at DESC, id DESC
LIMIT $8
`

type ListTasksByProjectAfterParams struct {
	ProjectID       uuid.UUID `json:"project_id"`
	TenantID        uuid.UUID `json:"tenant_id"`
	FilterStatus    *string   `json:"filter_status"`
	FilterPriority  *int32    `json:"filter_priority"`
	CursorPriority  int32     `json:"cursor_priority"`
	CursorCreatedAt time.Time `json:"cursor_created_at"`
	CursorID        uuid.UUID `json:"cursor_id"`
	LimitCount      int32     `json:"limit_count"`
}

func (q *Queries) ListTasksByProjectAfter(ctx context.Context, arg ListTasksByProjectAfterParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByProjectAfter,
		arg.ProjectID,
		arg.TenantID,
		arg.FilterStatus,
		arg.FilterPriority,
		arg.CursorPriority,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.AdrID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssignedTo,
			&i.AgentSessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionTask = `-- name: TransitionTask :one
UPDATE tasks SET status = $2, agent_session_id = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $4
RETURNING id, tenant_id, project_id, adr_id, title, description, status, priority, assigned_to, agent_session_id, created_at, updated_at
`

type TransitionTaskParams struct {
	ID             uuid.UUID   `json:"id"`
	Status         string      `json:"status"`
	AgentSessionID pgtype.UUID `json:"agent_session_id"`
	TenantID       uuid.UUID   `json:"tenant_id"`
}

func (q *Queries) TransitionTask(ctx context.Context, arg TransitionTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, transitionTask,
		arg.ID,
		arg.Status,
		arg.AgentSessionID,
		arg.TenantID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.AdrID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedTo,
		&i.AgentSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET title = $2, description = $3, priority = $4, assigned_to = $5, adr_id = $6, updated_at = now()
WHERE id = $1 AND tenant_id = $7
RETURNING id, tenant_id, project_id, adr_id, title, description, status, priority, assigned_to, agent_session_id, created_at, updated_at
`

type UpdateTaskParams struct {
	ID          uuid.UUID   `json:"id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Priority    int32       `json:"priority"`
	AssignedTo  pgtype.UUID `json:"assigned_to"`
	AdrID       pgtype.UUID `json:"adr_id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.AssignedTo,
		arg.AdrID,
		arg.TenantID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.AdrID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedTo,
		&i.AgentSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
