// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_oauth_links.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createOAuthLink = `-- name: CreateOAuthLink :one
INSERT INTO user_oauth_links (user_id, provider, provider_id, access_token, refresh_token)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, provider, provider_id, access_token, refresh_token, created_at
`

type CreateOAuthLinkParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Provider     string    `json:"provider"`
	ProviderID   string    `json:"provider_id"`
	AccessToken  *string   `json:"access_token"`
	RefreshToken *string   `json:"refresh_token"`
}

func (q *Queries) CreateOAuthLink(ctx context.Context, arg CreateOAuthLinkParams) (UserOauthLink, error) {
	row := q.db.QueryRow(ctx, createOAuthLink,
		arg.UserID,
		arg.Provider,
		arg.ProviderID,
		arg.AccessToken,
		arg.RefreshToken,
	)
	var i UserOauthLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOAuthLink = `-- name: DeleteOAuthLink :exec
DELETE FROM user_oauth_links WHERE id = $1
`

func (q *Queries) DeleteOAuthLink(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOAuthLink, id)
	return err
}

const getOAuthLinkByProvider = `-- name: GetOAuthLinkByProvider :one
SELECT id, user_id, provider, provider_id, access_token, refresh_token, created_at FROM user_oauth_links WHERE provider = $1 AND provider_id = $2
`

type GetOAuthLinkByProviderParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) GetOAuthLinkByProvider(ctx context.Context, arg GetOAuthLinkByProviderParams) (UserOauthLink, error) {
	row := q.db.QueryRow(ctx, getOAuthLinkByProvider, arg.Provider, arg.ProviderID)
	var i UserOauthLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.CreatedAt,
	)
	return i, err
}

const listOAuthLinksByUser = `-- name: ListOAuthLinksByUser :many
SELECT id, user_id, provider, provider_id, access_token, refresh_token, created_at FROM user_oauth_links WHERE user_id = $1
`

func (q *Queries) ListOAuthLinksByUser(ctx context.Context, userID uuid.UUID) ([]UserOauthLink, error) {
	rows, err := q.db.Query(ctx, listOAuthLinksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserOauthLink{}
	for rows.Next() {
		var i UserOauthLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
