// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_messenger_links.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createMessengerLink = `-- name: CreateMessengerLink :one
INSERT INTO user_messenger_links (user_id, tenant_id, platform, external_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, tenant_id, platform, external_id, created_at
`

type CreateMessengerLinkParams struct {
	UserID     uuid.UUID `json:"user_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Platform   string    `json:"platform"`
	ExternalID string    `json:"external_id"`
}

func (q *Queries) CreateMessengerLink(ctx context.Context, arg CreateMessengerLinkParams) (UserMessengerLink, error) {
	row := q.db.QueryRow(ctx, createMessengerLink,
		arg.UserID,
		arg.TenantID,
		arg.Platform,
		arg.ExternalID,
	)
	var i UserMessengerLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Platform,
		&i.ExternalID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessengerLinkByID = `-- name: DeleteMessengerLinkByID :one
DELETE FROM user_messenger_links
WHERE id = $1 AND user_id = $2 AND tenant_id = $3
RETURNING id, user_id, tenant_id, platform, external_id, created_at
`

type DeleteMessengerLinkByIDParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteMessengerLinkByID(ctx context.Context, arg DeleteMessengerLinkByIDParams) (UserMessengerLink, error) {
	row := q.db.QueryRow(ctx, deleteMessengerLinkByID, arg.ID, arg.UserID, arg.TenantID)
	var i UserMessengerLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Platform,
		&i.ExternalID,
		&i.CreatedAt,
	)
	return i, err
}

const getMessengerLink = `-- name: GetMessengerLink :one
SELECT id, user_id, tenant_id, platform, external_id, created_at FROM user_messenger_links
WHERE tenant_id = $1 AND platform = $2 AND external_id = $3
`

type GetMessengerLinkParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	Platform   string    `json:"platform"`
	ExternalID string    `json:"external_id"`
}

func (q *Queries) GetMessengerLink(ctx context.Context, arg GetMessengerLinkParams) (UserMessengerLink, error) {
	row := q.db.QueryRow(ctx, getMessengerLink, arg.TenantID, arg.Platform, arg.ExternalID)
	var i UserMessengerLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Platform,
		&i.ExternalID,
		&i.CreatedAt,
	)
	return i, err
}

const listMessengerLinksByUser = `-- name: ListMessengerLinksByUser :many
SELECT id, user_id, tenant_id, platform, external_id, created_at FROM user_messenger_links
WHERE user_id = $1 AND tenant_id = $2
ORDER BY created_at DESC, id DESC
`

type ListMessengerLinksByUserParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListMessengerLinksByUser(ctx context.Context, arg ListMessengerLinksByUserParams) ([]UserMessengerLink, error) {
	rows, err := q.db.Query(ctx, listMessengerLinksByUser, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserMessengerLink{}
	for rows.Next() {
		var i UserMessengerLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.Platform,
			&i.ExternalID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
